/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.LoginController;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import Servicio.ServiceLogin;

/**
 *
 * @author Carlos Orozco
 */
public class ViewLogin extends javax.swing.JFrame {
    
    private void mostrarpassword(){
    
        char echoChar = '*'; //caracteres a mostrar al no estar seleccionado el check
        
        String passwordTxt = String.valueOf(txtPassword.getPassword()); //carga el contenido de txtpassword(campo de contraseña)
        
        if (passwordTxt.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "El campo de contraseña esta vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);
            
            mostrarPassCheck.setSelected(false); //si el campo esta vacio no muestra la contraseña
            
        }
        
        if (mostrarPassCheck.isSelected()) {
            
            txtPassword.setEchoChar((char)0); //mostrar caracteres
            
        }else{
        
            txtPassword.setEchoChar(echoChar); //ocultar los caracteres
        
        }
    
    }

    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() {
        initComponents();
        
       this.setLocationRelativeTo(null); //centrar formulario en pantalla
       
      
    }
    
    //Metodos publicos para botones, getters
    
    public JTextField getTxtUsuario(){
       return txtUsuario;
    }
    
    public JPasswordField jPasswordField(){
    
        return txtPassword;
    }
    
    public JButton getBtnLogin(){
        return jbtLogin;
    }
    
    public JButton getBtnRecuperar(){
        return jbtRecuperar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jbtLogin = new javax.swing.JButton();
        jbtRecuperar = new javax.swing.JButton();
        mostrarPassCheck = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setTitle("Login Tecno-Ventas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(224, 224, 226));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(181, 186, 208));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(115, 137, 174));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(181, 186, 208));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuario.setText("XXXXXXXX");
        txtUsuario.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 260, 20));

        txtPassword.setBackground(new java.awt.Color(181, 186, 208));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPassword.setText("contraseña");
        txtPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 260, 20));

        jbtLogin.setBackground(new java.awt.Color(181, 186, 208));
        jbtLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtLogin.setText("Iniciar sesión");
        jbtLogin.setBorder(null);
        jbtLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtLoginMouseClicked(evt);
            }
        });
        jbtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLoginActionPerformed(evt);
            }
        });
        jPanel3.add(jbtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 280, 60));

        jbtRecuperar.setBackground(new java.awt.Color(115, 137, 174));
        jbtRecuperar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtRecuperar.setText("¿Olvidaste tu contraseña?");
        jbtRecuperar.setBorder(null);
        jbtRecuperar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jbtRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 170, 20));

        mostrarPassCheck.setBackground(new java.awt.Color(115, 137, 174));
        mostrarPassCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mostrarPassCheck.setBorder(null);
        mostrarPassCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarPassCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarPassCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ojo.png"))); // NOI18N
        mostrarPassCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarPassCheckMouseClicked(evt);
            }
        });
        mostrarPassCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPassCheckActionPerformed(evt);
            }
        });
        jPanel3.add(mostrarPassCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 30, 20));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 260, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(216, 219, 226));
        jLabel1.setText("Password:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 150, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(224, 224, 226));
        jLabel2.setText("¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 360, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(216, 219, 226));
        jLabel6.setText("Username:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 260, 20));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(224, 224, 226));
        jLabel7.setText("BIENVENIDO");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 230, 30));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(224, 224, 226));
        jLabel8.setText("¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 382, 471));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 550));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venta (1).png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, 230));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(115, 137, 174));
        jLabel5.setText("Tecno-Ventas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarPassCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPassCheckActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mostrarPassCheckActionPerformed

    private void mostrarPassCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarPassCheckMouseClicked
        // TODO add your handling code here:

        mostrarpassword();  //carga el metodo mostrar contraseña al dar clic
    }//GEN-LAST:event_mostrarPassCheckMouseClicked

    private void jbtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLoginActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbtLoginActionPerformed

    private void jbtLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtLoginMouseClicked

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        // TODO add your handling code here:

        //texto en blanco al recibir el enfoque

        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        // TODO add your handling code here:

        //texto en blanco al recibir el enfoque

        txtUsuario.setText("");

    }//GEN-LAST:event_txtUsuarioFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jbtLogin;
    private javax.swing.JButton jbtRecuperar;
    private javax.swing.JCheckBox mostrarPassCheck;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

  
}
